from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.certificate_type import CertificateType
from ..types import UNSET, Unset

T = TypeVar("T", bound="Certificate")


@_attrs_define
class Certificate:
    """
    Attributes:
        descr (str | Unset): The descriptive name for this certificate.<br>
        refid (None | str | Unset): The unique ID assigned to this certificate for internal system use. This value is
            generated by this system and cannot be changed.<br>
        caref (None | str | Unset): The unique ID of the existing pfSense Certificate Authority that signed this
            certificate.This value is assigned by this system and cannot be changed.<br>
        type_ (CertificateType | Unset): The certificate type. Use `server` when this certificate is to be used by one
            or more services on this system. Use `user` when this certificate is intended to be assigned to a user for
            authentication purposes.<br> Default: CertificateType.SERVER.
        csr (None | str | Unset): The X509 certificate signing request string if this certificate is pending an external
            signature.<br>
        crt (str | Unset): The X509 certificate string.<br>
        prv (str | Unset): The X509 private key string.<br>
        valid_from (None | str | Unset): The start date from which this certificate is valid.<br>
        valid_until (None | str | Unset): The date until which this certificate is valid.<br>
        valid_days_left (int | None | Unset): The number of days remaining until this certificate expires.<br>
    """

    descr: str | Unset = UNSET
    refid: None | str | Unset = UNSET
    caref: None | str | Unset = UNSET
    type_: CertificateType | Unset = CertificateType.SERVER
    csr: None | str | Unset = UNSET
    crt: str | Unset = UNSET
    prv: str | Unset = UNSET
    valid_from: None | str | Unset = UNSET
    valid_until: None | str | Unset = UNSET
    valid_days_left: int | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        descr = self.descr

        refid: None | str | Unset
        if isinstance(self.refid, Unset):
            refid = UNSET
        else:
            refid = self.refid

        caref: None | str | Unset
        if isinstance(self.caref, Unset):
            caref = UNSET
        else:
            caref = self.caref

        type_: str | Unset = UNSET
        if not isinstance(self.type_, Unset):
            type_ = self.type_.value

        csr: None | str | Unset
        if isinstance(self.csr, Unset):
            csr = UNSET
        else:
            csr = self.csr

        crt = self.crt

        prv = self.prv

        valid_from: None | str | Unset
        if isinstance(self.valid_from, Unset):
            valid_from = UNSET
        else:
            valid_from = self.valid_from

        valid_until: None | str | Unset
        if isinstance(self.valid_until, Unset):
            valid_until = UNSET
        else:
            valid_until = self.valid_until

        valid_days_left: int | None | Unset
        if isinstance(self.valid_days_left, Unset):
            valid_days_left = UNSET
        else:
            valid_days_left = self.valid_days_left

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if descr is not UNSET:
            field_dict["descr"] = descr
        if refid is not UNSET:
            field_dict["refid"] = refid
        if caref is not UNSET:
            field_dict["caref"] = caref
        if type_ is not UNSET:
            field_dict["type"] = type_
        if csr is not UNSET:
            field_dict["csr"] = csr
        if crt is not UNSET:
            field_dict["crt"] = crt
        if prv is not UNSET:
            field_dict["prv"] = prv
        if valid_from is not UNSET:
            field_dict["valid_from"] = valid_from
        if valid_until is not UNSET:
            field_dict["valid_until"] = valid_until
        if valid_days_left is not UNSET:
            field_dict["valid_days_left"] = valid_days_left

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        descr = d.pop("descr", UNSET)

        def _parse_refid(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        refid = _parse_refid(d.pop("refid", UNSET))

        def _parse_caref(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        caref = _parse_caref(d.pop("caref", UNSET))

        _type_ = d.pop("type", UNSET)
        type_: CertificateType | Unset
        if isinstance(_type_, Unset):
            type_ = UNSET
        else:
            type_ = CertificateType(_type_)

        def _parse_csr(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        csr = _parse_csr(d.pop("csr", UNSET))

        crt = d.pop("crt", UNSET)

        prv = d.pop("prv", UNSET)

        def _parse_valid_from(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        valid_from = _parse_valid_from(d.pop("valid_from", UNSET))

        def _parse_valid_until(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        valid_until = _parse_valid_until(d.pop("valid_until", UNSET))

        def _parse_valid_days_left(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        valid_days_left = _parse_valid_days_left(d.pop("valid_days_left", UNSET))

        certificate = cls(
            descr=descr,
            refid=refid,
            caref=caref,
            type_=type_,
            csr=csr,
            crt=crt,
            prv=prv,
            valid_from=valid_from,
            valid_until=valid_until,
            valid_days_left=valid_days_left,
        )

        certificate.additional_properties = d
        return certificate

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
