from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="CertificateAuthority")


@_attrs_define
class CertificateAuthority:
    """
    Attributes:
        descr (str | Unset): The descriptive name for this certificate authority.<br>
        refid (None | str | Unset): The unique ID assigned to this certificate authority for internal system use. This
            value is generated by this system and cannot be changed.<br>
        caref (None | str | Unset): The reference ID of the assigned root certificate authority.<br>
        trust (bool | Unset): Adds or removes this certificate authority from the operating system's trust stored.<br>
        randomserial (bool | Unset): Enables or disables the randomization of serial numbers for certificates signed by
            this CA.<br>
        serial (int | Unset): The decimal number to be used as a sequential serial number for the next certificate to be
            signed by this CA. This value is ignored when Randomize Serial is checked.<br> Default: 1.
        crt (str | Unset): The X509 certificate string.<br>
        prv (None | str | Unset): The X509 private key string.<br>
    """

    descr: str | Unset = UNSET
    refid: None | str | Unset = UNSET
    caref: None | str | Unset = UNSET
    trust: bool | Unset = UNSET
    randomserial: bool | Unset = UNSET
    serial: int | Unset = 1
    crt: str | Unset = UNSET
    prv: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        descr = self.descr

        refid: None | str | Unset
        if isinstance(self.refid, Unset):
            refid = UNSET
        else:
            refid = self.refid

        caref: None | str | Unset
        if isinstance(self.caref, Unset):
            caref = UNSET
        else:
            caref = self.caref

        trust = self.trust

        randomserial = self.randomserial

        serial = self.serial

        crt = self.crt

        prv: None | str | Unset
        if isinstance(self.prv, Unset):
            prv = UNSET
        else:
            prv = self.prv

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if descr is not UNSET:
            field_dict["descr"] = descr
        if refid is not UNSET:
            field_dict["refid"] = refid
        if caref is not UNSET:
            field_dict["caref"] = caref
        if trust is not UNSET:
            field_dict["trust"] = trust
        if randomserial is not UNSET:
            field_dict["randomserial"] = randomserial
        if serial is not UNSET:
            field_dict["serial"] = serial
        if crt is not UNSET:
            field_dict["crt"] = crt
        if prv is not UNSET:
            field_dict["prv"] = prv

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        descr = d.pop("descr", UNSET)

        def _parse_refid(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        refid = _parse_refid(d.pop("refid", UNSET))

        def _parse_caref(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        caref = _parse_caref(d.pop("caref", UNSET))

        trust = d.pop("trust", UNSET)

        randomserial = d.pop("randomserial", UNSET)

        serial = d.pop("serial", UNSET)

        crt = d.pop("crt", UNSET)

        def _parse_prv(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        prv = _parse_prv(d.pop("prv", UNSET))

        certificate_authority = cls(
            descr=descr,
            refid=refid,
            caref=caref,
            trust=trust,
            randomserial=randomserial,
            serial=serial,
            crt=crt,
            prv=prv,
        )

        certificate_authority.additional_properties = d
        return certificate_authority

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
