from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.certificate_signing_request_keylen import CertificateSigningRequestKeylen
from ..models.certificate_signing_request_keytype import CertificateSigningRequestKeytype
from ..models.certificate_signing_request_type import CertificateSigningRequestType
from ..types import UNSET, Unset

T = TypeVar("T", bound="CertificateSigningRequest")


@_attrs_define
class CertificateSigningRequest:
    """
    Attributes:
        descr (str | Unset): The descriptive name for this certificate.<br>
        refid (None | str | Unset): The unique ID assigned to this certificate for internal system use. This value is
            generated by this system and cannot be changed.<br>
        keytype (CertificateSigningRequestKeytype | Unset): The type of key pair to generate.<br>
        keylen (CertificateSigningRequestKeylen | Unset): The length of the RSA key pair to generate.<br><br>This field
            is only available when the following conditions are met:<br>- `keytype` must be equal to `'RSA'`<br>
        ecname (str | Unset): The name of the elliptic curve to use for the ECDSA key pair.<br><br>This field is only
            available when the following conditions are met:<br>- `keytype` must be equal to `'ECDSA'`<br>
        digest_alg (str | Unset): The digest method used when the certificate is signed.<br>
        lifetime (int | Unset): The number of days the certificate is valid for.<br> Default: 3650.
        dn_commonname (str | Unset): The common name of the certificate.<br>
        dn_country (None | str | Unset): The country of the certificate.<br>
        dn_state (None | str | Unset): The state/province of the certificate.<br>
        dn_city (None | str | Unset): The city of the certificate.<br>
        dn_organization (None | str | Unset): The organization of the certificate.<br>
        dn_organizationalunit (None | str | Unset): The organizational unit of the certificate.<br>
        type_ (CertificateSigningRequestType | Unset): The type of certificate to generate.<br> Default:
            CertificateSigningRequestType.USER.
        dn_dns_sans (list[str] | Unset): The DNS Subject Alternative Names (SANs) for the certificate.<br>
        dn_email_sans (list[str] | Unset): The Email Subject Alternative Names (SANs) for the certificate.<br>
        dn_ip_sans (list[str] | Unset): The IP Subject Alternative Names (SANs) for the certificate.<br>
        dn_uri_sans (list[str] | Unset): The URI Subject Alternative Names (SANs) for the certificate.<br>
        csr (None | str | Unset): The X509 certificate signing request string. You will need to provide this to a
            certificate authority to sign the certificate.<br>
        prv (None | str | Unset): The X509 private key string.<br>
    """

    descr: str | Unset = UNSET
    refid: None | str | Unset = UNSET
    keytype: CertificateSigningRequestKeytype | Unset = UNSET
    keylen: CertificateSigningRequestKeylen | Unset = UNSET
    ecname: str | Unset = UNSET
    digest_alg: str | Unset = UNSET
    lifetime: int | Unset = 3650
    dn_commonname: str | Unset = UNSET
    dn_country: None | str | Unset = UNSET
    dn_state: None | str | Unset = UNSET
    dn_city: None | str | Unset = UNSET
    dn_organization: None | str | Unset = UNSET
    dn_organizationalunit: None | str | Unset = UNSET
    type_: CertificateSigningRequestType | Unset = CertificateSigningRequestType.USER
    dn_dns_sans: list[str] | Unset = UNSET
    dn_email_sans: list[str] | Unset = UNSET
    dn_ip_sans: list[str] | Unset = UNSET
    dn_uri_sans: list[str] | Unset = UNSET
    csr: None | str | Unset = UNSET
    prv: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        descr = self.descr

        refid: None | str | Unset
        if isinstance(self.refid, Unset):
            refid = UNSET
        else:
            refid = self.refid

        keytype: str | Unset = UNSET
        if not isinstance(self.keytype, Unset):
            keytype = self.keytype.value

        keylen: int | Unset = UNSET
        if not isinstance(self.keylen, Unset):
            keylen = self.keylen.value

        ecname = self.ecname

        digest_alg = self.digest_alg

        lifetime = self.lifetime

        dn_commonname = self.dn_commonname

        dn_country: None | str | Unset
        if isinstance(self.dn_country, Unset):
            dn_country = UNSET
        else:
            dn_country = self.dn_country

        dn_state: None | str | Unset
        if isinstance(self.dn_state, Unset):
            dn_state = UNSET
        else:
            dn_state = self.dn_state

        dn_city: None | str | Unset
        if isinstance(self.dn_city, Unset):
            dn_city = UNSET
        else:
            dn_city = self.dn_city

        dn_organization: None | str | Unset
        if isinstance(self.dn_organization, Unset):
            dn_organization = UNSET
        else:
            dn_organization = self.dn_organization

        dn_organizationalunit: None | str | Unset
        if isinstance(self.dn_organizationalunit, Unset):
            dn_organizationalunit = UNSET
        else:
            dn_organizationalunit = self.dn_organizationalunit

        type_: str | Unset = UNSET
        if not isinstance(self.type_, Unset):
            type_ = self.type_.value

        dn_dns_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_dns_sans, Unset):
            dn_dns_sans = self.dn_dns_sans

        dn_email_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_email_sans, Unset):
            dn_email_sans = self.dn_email_sans

        dn_ip_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_ip_sans, Unset):
            dn_ip_sans = self.dn_ip_sans

        dn_uri_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_uri_sans, Unset):
            dn_uri_sans = self.dn_uri_sans

        csr: None | str | Unset
        if isinstance(self.csr, Unset):
            csr = UNSET
        else:
            csr = self.csr

        prv: None | str | Unset
        if isinstance(self.prv, Unset):
            prv = UNSET
        else:
            prv = self.prv

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if descr is not UNSET:
            field_dict["descr"] = descr
        if refid is not UNSET:
            field_dict["refid"] = refid
        if keytype is not UNSET:
            field_dict["keytype"] = keytype
        if keylen is not UNSET:
            field_dict["keylen"] = keylen
        if ecname is not UNSET:
            field_dict["ecname"] = ecname
        if digest_alg is not UNSET:
            field_dict["digest_alg"] = digest_alg
        if lifetime is not UNSET:
            field_dict["lifetime"] = lifetime
        if dn_commonname is not UNSET:
            field_dict["dn_commonname"] = dn_commonname
        if dn_country is not UNSET:
            field_dict["dn_country"] = dn_country
        if dn_state is not UNSET:
            field_dict["dn_state"] = dn_state
        if dn_city is not UNSET:
            field_dict["dn_city"] = dn_city
        if dn_organization is not UNSET:
            field_dict["dn_organization"] = dn_organization
        if dn_organizationalunit is not UNSET:
            field_dict["dn_organizationalunit"] = dn_organizationalunit
        if type_ is not UNSET:
            field_dict["type"] = type_
        if dn_dns_sans is not UNSET:
            field_dict["dn_dns_sans"] = dn_dns_sans
        if dn_email_sans is not UNSET:
            field_dict["dn_email_sans"] = dn_email_sans
        if dn_ip_sans is not UNSET:
            field_dict["dn_ip_sans"] = dn_ip_sans
        if dn_uri_sans is not UNSET:
            field_dict["dn_uri_sans"] = dn_uri_sans
        if csr is not UNSET:
            field_dict["csr"] = csr
        if prv is not UNSET:
            field_dict["prv"] = prv

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        descr = d.pop("descr", UNSET)

        def _parse_refid(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        refid = _parse_refid(d.pop("refid", UNSET))

        _keytype = d.pop("keytype", UNSET)
        keytype: CertificateSigningRequestKeytype | Unset
        if isinstance(_keytype, Unset):
            keytype = UNSET
        else:
            keytype = CertificateSigningRequestKeytype(_keytype)

        _keylen = d.pop("keylen", UNSET)
        keylen: CertificateSigningRequestKeylen | Unset
        if isinstance(_keylen, Unset):
            keylen = UNSET
        else:
            keylen = CertificateSigningRequestKeylen(_keylen)

        ecname = d.pop("ecname", UNSET)

        digest_alg = d.pop("digest_alg", UNSET)

        lifetime = d.pop("lifetime", UNSET)

        dn_commonname = d.pop("dn_commonname", UNSET)

        def _parse_dn_country(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        dn_country = _parse_dn_country(d.pop("dn_country", UNSET))

        def _parse_dn_state(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        dn_state = _parse_dn_state(d.pop("dn_state", UNSET))

        def _parse_dn_city(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        dn_city = _parse_dn_city(d.pop("dn_city", UNSET))

        def _parse_dn_organization(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        dn_organization = _parse_dn_organization(d.pop("dn_organization", UNSET))

        def _parse_dn_organizationalunit(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        dn_organizationalunit = _parse_dn_organizationalunit(d.pop("dn_organizationalunit", UNSET))

        _type_ = d.pop("type", UNSET)
        type_: CertificateSigningRequestType | Unset
        if isinstance(_type_, Unset):
            type_ = UNSET
        else:
            type_ = CertificateSigningRequestType(_type_)

        dn_dns_sans = cast(list[str], d.pop("dn_dns_sans", UNSET))

        dn_email_sans = cast(list[str], d.pop("dn_email_sans", UNSET))

        dn_ip_sans = cast(list[str], d.pop("dn_ip_sans", UNSET))

        dn_uri_sans = cast(list[str], d.pop("dn_uri_sans", UNSET))

        def _parse_csr(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        csr = _parse_csr(d.pop("csr", UNSET))

        def _parse_prv(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        prv = _parse_prv(d.pop("prv", UNSET))

        certificate_signing_request = cls(
            descr=descr,
            refid=refid,
            keytype=keytype,
            keylen=keylen,
            ecname=ecname,
            digest_alg=digest_alg,
            lifetime=lifetime,
            dn_commonname=dn_commonname,
            dn_country=dn_country,
            dn_state=dn_state,
            dn_city=dn_city,
            dn_organization=dn_organization,
            dn_organizationalunit=dn_organizationalunit,
            type_=type_,
            dn_dns_sans=dn_dns_sans,
            dn_email_sans=dn_email_sans,
            dn_ip_sans=dn_ip_sans,
            dn_uri_sans=dn_uri_sans,
            csr=csr,
            prv=prv,
        )

        certificate_signing_request.additional_properties = d
        return certificate_signing_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
