from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.certificate_signing_request_sign_type import CertificateSigningRequestSignType
from ..types import UNSET, Unset

T = TypeVar("T", bound="CertificateSigningRequestSign")


@_attrs_define
class CertificateSigningRequestSign:
    """
    Attributes:
        descr (str | Unset): The descriptive name for this certificate.<br>
        refid (None | str | Unset): The unique ID assigned to this certificate for internal system use. This value is
            generated by this system and cannot be changed.<br>
        caref (str | Unset): The certificate authority to sign the certificate with.<br>
        csr (str | Unset): The X509 certificate signing request to sign.<br>
        crt (None | str | Unset): The X509 certificate string.<br>
        prv (None | str | Unset): The X509 private key string.<br>
        digest_alg (str | Unset): The digest method used when the certificate is signed.<br>
        lifetime (int | Unset): The number of days the certificate is valid for.<br> Default: 3650.
        type_ (CertificateSigningRequestSignType | Unset): The type of certificate to generate.<br> Default:
            CertificateSigningRequestSignType.USER.
        dn_dns_sans (list[str] | Unset): The DNS Subject Alternative Names (SANs) for the certificate.<br>
        dn_email_sans (list[str] | Unset): The Email Subject Alternative Names (SANs) for the certificate.<br>
        dn_ip_sans (list[str] | Unset): The IP Subject Alternative Names (SANs) for the certificate.<br>
        dn_uri_sans (list[str] | Unset): The URI Subject Alternative Names (SANs) for the certificate.<br>
    """

    descr: str | Unset = UNSET
    refid: None | str | Unset = UNSET
    caref: str | Unset = UNSET
    csr: str | Unset = UNSET
    crt: None | str | Unset = UNSET
    prv: None | str | Unset = UNSET
    digest_alg: str | Unset = UNSET
    lifetime: int | Unset = 3650
    type_: CertificateSigningRequestSignType | Unset = CertificateSigningRequestSignType.USER
    dn_dns_sans: list[str] | Unset = UNSET
    dn_email_sans: list[str] | Unset = UNSET
    dn_ip_sans: list[str] | Unset = UNSET
    dn_uri_sans: list[str] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        descr = self.descr

        refid: None | str | Unset
        if isinstance(self.refid, Unset):
            refid = UNSET
        else:
            refid = self.refid

        caref = self.caref

        csr = self.csr

        crt: None | str | Unset
        if isinstance(self.crt, Unset):
            crt = UNSET
        else:
            crt = self.crt

        prv: None | str | Unset
        if isinstance(self.prv, Unset):
            prv = UNSET
        else:
            prv = self.prv

        digest_alg = self.digest_alg

        lifetime = self.lifetime

        type_: str | Unset = UNSET
        if not isinstance(self.type_, Unset):
            type_ = self.type_.value

        dn_dns_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_dns_sans, Unset):
            dn_dns_sans = self.dn_dns_sans

        dn_email_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_email_sans, Unset):
            dn_email_sans = self.dn_email_sans

        dn_ip_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_ip_sans, Unset):
            dn_ip_sans = self.dn_ip_sans

        dn_uri_sans: list[str] | Unset = UNSET
        if not isinstance(self.dn_uri_sans, Unset):
            dn_uri_sans = self.dn_uri_sans

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if descr is not UNSET:
            field_dict["descr"] = descr
        if refid is not UNSET:
            field_dict["refid"] = refid
        if caref is not UNSET:
            field_dict["caref"] = caref
        if csr is not UNSET:
            field_dict["csr"] = csr
        if crt is not UNSET:
            field_dict["crt"] = crt
        if prv is not UNSET:
            field_dict["prv"] = prv
        if digest_alg is not UNSET:
            field_dict["digest_alg"] = digest_alg
        if lifetime is not UNSET:
            field_dict["lifetime"] = lifetime
        if type_ is not UNSET:
            field_dict["type"] = type_
        if dn_dns_sans is not UNSET:
            field_dict["dn_dns_sans"] = dn_dns_sans
        if dn_email_sans is not UNSET:
            field_dict["dn_email_sans"] = dn_email_sans
        if dn_ip_sans is not UNSET:
            field_dict["dn_ip_sans"] = dn_ip_sans
        if dn_uri_sans is not UNSET:
            field_dict["dn_uri_sans"] = dn_uri_sans

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        descr = d.pop("descr", UNSET)

        def _parse_refid(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        refid = _parse_refid(d.pop("refid", UNSET))

        caref = d.pop("caref", UNSET)

        csr = d.pop("csr", UNSET)

        def _parse_crt(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        crt = _parse_crt(d.pop("crt", UNSET))

        def _parse_prv(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        prv = _parse_prv(d.pop("prv", UNSET))

        digest_alg = d.pop("digest_alg", UNSET)

        lifetime = d.pop("lifetime", UNSET)

        _type_ = d.pop("type", UNSET)
        type_: CertificateSigningRequestSignType | Unset
        if isinstance(_type_, Unset):
            type_ = UNSET
        else:
            type_ = CertificateSigningRequestSignType(_type_)

        dn_dns_sans = cast(list[str], d.pop("dn_dns_sans", UNSET))

        dn_email_sans = cast(list[str], d.pop("dn_email_sans", UNSET))

        dn_ip_sans = cast(list[str], d.pop("dn_ip_sans", UNSET))

        dn_uri_sans = cast(list[str], d.pop("dn_uri_sans", UNSET))

        certificate_signing_request_sign = cls(
            descr=descr,
            refid=refid,
            caref=caref,
            csr=csr,
            crt=crt,
            prv=prv,
            digest_alg=digest_alg,
            lifetime=lifetime,
            type_=type_,
            dn_dns_sans=dn_dns_sans,
            dn_email_sans=dn_email_sans,
            dn_ip_sans=dn_ip_sans,
            dn_uri_sans=dn_uri_sans,
        )

        certificate_signing_request_sign.additional_properties = d
        return certificate_signing_request_sign

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
