from enum import Enum


class HAProxyFrontendActionAction(str, Enum):
    CUSTOM = "custom"
    HTTP_AFTER_RESPONSE_ADD_HEADER = "http-after-response_add-header"
    HTTP_AFTER_RESPONSE_DEL_HEADER = "http-after-response_del-header"
    HTTP_AFTER_RESPONSE_REPLACE_HEADER = "http-after-response_replace-header"
    HTTP_AFTER_RESPONSE_REPLACE_VALUE = "http-after-response_replace-value"
    HTTP_AFTER_RESPONSE_SET_HEADER = "http-after-response_set-header"
    HTTP_AFTER_RESPONSE_SET_STATUS = "http-after-response_set-status"
    HTTP_REQUEST_ADD_HEADER = "http-request_add-header"
    HTTP_REQUEST_ALLOW = "http-request_allow"
    HTTP_REQUEST_AUTH = "http-request_auth"
    HTTP_REQUEST_DEL_HEADER = "http-request_del-header"
    HTTP_REQUEST_DENY = "http-request_deny"
    HTTP_REQUEST_LUA = "http-request_lua"
    HTTP_REQUEST_REDIRECT = "http-request_redirect"
    HTTP_REQUEST_REPLACE_HEADER = "http-request_replace-header"
    HTTP_REQUEST_REPLACE_PATH = "http-request_replace-path"
    HTTP_REQUEST_REPLACE_VALUE = "http-request_replace-value"
    HTTP_REQUEST_SET_HEADER = "http-request_set-header"
    HTTP_REQUEST_SET_METHOD = "http-request_set-method"
    HTTP_REQUEST_SET_PATH = "http-request_set-path"
    HTTP_REQUEST_SET_QUERY = "http-request_set-query"
    HTTP_REQUEST_SET_URI = "http-request_set-uri"
    HTTP_REQUEST_TARPIT = "http-request_tarpit"
    HTTP_REQUEST_USE_SERVICE = "http-request_use-service"
    HTTP_RESPONSE_ADD_HEADER = "http-response_add-header"
    HTTP_RESPONSE_ALLOW = "http-response_allow"
    HTTP_RESPONSE_DEL_HEADER = "http-response_del-header"
    HTTP_RESPONSE_DENY = "http-response_deny"
    HTTP_RESPONSE_LUA = "http-response_lua"
    HTTP_RESPONSE_REPLACE_HEADER = "http-response_replace-header"
    HTTP_RESPONSE_REPLACE_VALUE = "http-response_replace-value"
    HTTP_RESPONSE_SET_HEADER = "http-response_set-header"
    HTTP_RESPONSE_SET_STATUS = "http-response_set-status"
    TCP_REQUEST_CONNECTION_ACCEPT = "tcp-request_connection_accept"
    TCP_REQUEST_CONNECTION_REJECT = "tcp-request_connection_reject"
    TCP_REQUEST_CONTENT_ACCEPT = "tcp-request_content_accept"
    TCP_REQUEST_CONTENT_LUA = "tcp-request_content_lua"
    TCP_REQUEST_CONTENT_REJECT = "tcp-request_content_reject"
    TCP_REQUEST_CONTENT_USE_SERVICE = "tcp-request_content_use-service"
    TCP_RESPONSE_CONTENT_ACCEPT = "tcp-response_content_accept"
    TCP_RESPONSE_CONTENT_CLOSE = "tcp-response_content_close"
    TCP_RESPONSE_CONTENT_LUA = "tcp-response_content_lua"
    TCP_RESPONSE_CONTENT_REJECT = "tcp-response_content_reject"
    USE_BACKEND = "use_backend"

    def __str__(self) -> str:
        return str(self.value)
