from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.log_settings_filterdescriptions import LogSettingsFilterdescriptions
from ..models.log_settings_format import LogSettingsFormat
from ..models.log_settings_ipprotocol import LogSettingsIpprotocol
from ..models.log_settings_logcompressiontype import LogSettingsLogcompressiontype
from ..types import UNSET, Unset

T = TypeVar("T", bound="PatchStatusLogsSettingsEndpointDataBody")


@_attrs_define
class PatchStatusLogsSettingsEndpointDataBody:
    """
    Attributes:
        format_ (LogSettingsFormat | Unset): The format of the log entries.<br> Default: LogSettingsFormat.RFC3164.
        reverseorder (bool | Unset): Reverse the order of log entries.<br>
        nentries (int | Unset): The number of log entries to display in the UI.<br> Default: 500.
        nologdefaultblock (bool | Unset): Do not log packets that are blocked by the implicit default block rule.<br>
        nologdefaultpass (bool | Unset): Do not log packets that are allowed by the implicit default pass rule.<br>
        nologbogons (bool | Unset): Log packets blocked by Block Bogon Networks rules.<br>
        nologprivatenets (bool | Unset): Log packets blocked by Block Private Networks rules.<br>
        nolognginx (bool | Unset): Do not Log errors from the web server process.<br>
        rawfilter (bool | Unset): Display logs in the UI as they are generated by the packet filter, without any
            formatting.<br>
        disablelocallogging (bool | Unset): Disable writing log entries to the local disk. WARNING: This will also
            disable Login Protection!<br>
        logconfigchanges (bool | Unset): Log changes made to the pfSense configuration.<br>
        filterdescriptions (LogSettingsFilterdescriptions | Unset): Display filter descriptions in the log entries Use
            `0` to not load descriptions, `1` to display descriptions in their own column, or `2` to display the description
            in a second row.<br>
        logfilesize (int | Unset): The maximum size of the log file in kilobytes.<br> Default: 512000.
        rotatecount (int | Unset): The number of log file rotations to keep.<br> Default: 5.
        logcompressiontype (LogSettingsLogcompressiontype | Unset): The type of compression to use for log files.<br>
            Default: LogSettingsLogcompressiontype.BZIP2.
        enableremotelogging (bool | Unset): Enable remote logging.<br>
        ipprotocol (LogSettingsIpprotocol | Unset): The IP protocol to use for remote logging.<br><br>This field is only
            available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br> Default:
            LogSettingsIpprotocol.IPV4.
        sourceip (str | Unset): The interface to use as the source IP address for remote logging.<br><br>This field is
            only available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>
        remoteserver (None | str | Unset): The first remote syslog server to send log entries to.<br><br>This field is
            only available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>
        remoteserver2 (None | str | Unset): The second remote syslog server to send log entries to.<br><br>This field is
            only available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>-
            `remoteserver` must not be equal to `NULL`<br>
        remoteserver3 (None | str | Unset): The third remote syslog server to send log entries to.<br><br>This field is
            only available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>-
            `remoteserver` must not be equal to `NULL`<br>- `remoteserver2` must not be equal to `NULL`<br>
        logall (bool | Unset): Log everything to the remote syslog server(s).<br><br>This field is only available when
            the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>
        filter_ (bool | Unset): Log filter events to the remote syslog server(s).<br><br>This field is only available
            when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>- `logall` must not
            be equal to `true`<br>
        dhcp (bool | Unset): Log DHCP events to the remote syslog server(s).<br><br>This field is only available when
            the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>- `logall` must not be
            equal to `true`<br>
        auth (bool | Unset): Log authentication events to the remote syslog server(s).<br><br>This field is only
            available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>-
            `logall` must not be equal to `true`<br>
        portalauth (bool | Unset): Log captive portal authentication events to the remote syslog server(s).<br><br>This
            field is only available when the following conditions are met:<br>- `enableremotelogging` must be equal to
            `true`<br>- `logall` must not be equal to `true`<br>
        vpn (bool | Unset): Log VPN events to the remote syslog server(s).<br><br>This field is only available when the
            following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>- `logall` must not be equal
            to `true`<br>
        dpinger (bool | Unset): Log gateway monitoring events to the remote syslog server(s).<br><br>This field is only
            available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>-
            `logall` must not be equal to `true`<br>
        hostapd (bool | Unset): Log wireless authentication events to the remote syslog server(s).<br><br>This field is
            only available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>-
            `logall` must not be equal to `true`<br>
        system (bool | Unset): Log system events to the remote syslog server(s).<br><br>This field is only available
            when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>- `logall` must not
            be equal to `true`<br>
        resolver (bool | Unset): Log DNS resolver events to the remote syslog server(s).<br><br>This field is only
            available when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>-
            `logall` must not be equal to `true`<br>
        ppp (bool | Unset): Log PPP events to the remote syslog server(s).<br><br>This field is only available when the
            following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>- `logall` must not be equal
            to `true`<br>
        routing (bool | Unset): Log routing events to the remote syslog server(s).<br><br>This field is only available
            when the following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>- `logall` must not
            be equal to `true`<br>
        ntpd (bool | Unset): Log NTP events to the remote syslog server(s).<br><br>This field is only available when the
            following conditions are met:<br>- `enableremotelogging` must be equal to `true`<br>- `logall` must not be equal
            to `true`<br>
    """

    format_: LogSettingsFormat | Unset = LogSettingsFormat.RFC3164
    reverseorder: bool | Unset = UNSET
    nentries: int | Unset = 500
    nologdefaultblock: bool | Unset = UNSET
    nologdefaultpass: bool | Unset = UNSET
    nologbogons: bool | Unset = UNSET
    nologprivatenets: bool | Unset = UNSET
    nolognginx: bool | Unset = UNSET
    rawfilter: bool | Unset = UNSET
    disablelocallogging: bool | Unset = UNSET
    logconfigchanges: bool | Unset = UNSET
    filterdescriptions: LogSettingsFilterdescriptions | Unset = UNSET
    logfilesize: int | Unset = 512000
    rotatecount: int | Unset = 5
    logcompressiontype: LogSettingsLogcompressiontype | Unset = LogSettingsLogcompressiontype.BZIP2
    enableremotelogging: bool | Unset = UNSET
    ipprotocol: LogSettingsIpprotocol | Unset = LogSettingsIpprotocol.IPV4
    sourceip: str | Unset = UNSET
    remoteserver: None | str | Unset = UNSET
    remoteserver2: None | str | Unset = UNSET
    remoteserver3: None | str | Unset = UNSET
    logall: bool | Unset = UNSET
    filter_: bool | Unset = UNSET
    dhcp: bool | Unset = UNSET
    auth: bool | Unset = UNSET
    portalauth: bool | Unset = UNSET
    vpn: bool | Unset = UNSET
    dpinger: bool | Unset = UNSET
    hostapd: bool | Unset = UNSET
    system: bool | Unset = UNSET
    resolver: bool | Unset = UNSET
    ppp: bool | Unset = UNSET
    routing: bool | Unset = UNSET
    ntpd: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        format_: str | Unset = UNSET
        if not isinstance(self.format_, Unset):
            format_ = self.format_.value

        reverseorder = self.reverseorder

        nentries = self.nentries

        nologdefaultblock = self.nologdefaultblock

        nologdefaultpass = self.nologdefaultpass

        nologbogons = self.nologbogons

        nologprivatenets = self.nologprivatenets

        nolognginx = self.nolognginx

        rawfilter = self.rawfilter

        disablelocallogging = self.disablelocallogging

        logconfigchanges = self.logconfigchanges

        filterdescriptions: int | Unset = UNSET
        if not isinstance(self.filterdescriptions, Unset):
            filterdescriptions = self.filterdescriptions.value

        logfilesize = self.logfilesize

        rotatecount = self.rotatecount

        logcompressiontype: str | Unset = UNSET
        if not isinstance(self.logcompressiontype, Unset):
            logcompressiontype = self.logcompressiontype.value

        enableremotelogging = self.enableremotelogging

        ipprotocol: str | Unset = UNSET
        if not isinstance(self.ipprotocol, Unset):
            ipprotocol = self.ipprotocol.value

        sourceip = self.sourceip

        remoteserver: None | str | Unset
        if isinstance(self.remoteserver, Unset):
            remoteserver = UNSET
        else:
            remoteserver = self.remoteserver

        remoteserver2: None | str | Unset
        if isinstance(self.remoteserver2, Unset):
            remoteserver2 = UNSET
        else:
            remoteserver2 = self.remoteserver2

        remoteserver3: None | str | Unset
        if isinstance(self.remoteserver3, Unset):
            remoteserver3 = UNSET
        else:
            remoteserver3 = self.remoteserver3

        logall = self.logall

        filter_ = self.filter_

        dhcp = self.dhcp

        auth = self.auth

        portalauth = self.portalauth

        vpn = self.vpn

        dpinger = self.dpinger

        hostapd = self.hostapd

        system = self.system

        resolver = self.resolver

        ppp = self.ppp

        routing = self.routing

        ntpd = self.ntpd

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if format_ is not UNSET:
            field_dict["format"] = format_
        if reverseorder is not UNSET:
            field_dict["reverseorder"] = reverseorder
        if nentries is not UNSET:
            field_dict["nentries"] = nentries
        if nologdefaultblock is not UNSET:
            field_dict["nologdefaultblock"] = nologdefaultblock
        if nologdefaultpass is not UNSET:
            field_dict["nologdefaultpass"] = nologdefaultpass
        if nologbogons is not UNSET:
            field_dict["nologbogons"] = nologbogons
        if nologprivatenets is not UNSET:
            field_dict["nologprivatenets"] = nologprivatenets
        if nolognginx is not UNSET:
            field_dict["nolognginx"] = nolognginx
        if rawfilter is not UNSET:
            field_dict["rawfilter"] = rawfilter
        if disablelocallogging is not UNSET:
            field_dict["disablelocallogging"] = disablelocallogging
        if logconfigchanges is not UNSET:
            field_dict["logconfigchanges"] = logconfigchanges
        if filterdescriptions is not UNSET:
            field_dict["filterdescriptions"] = filterdescriptions
        if logfilesize is not UNSET:
            field_dict["logfilesize"] = logfilesize
        if rotatecount is not UNSET:
            field_dict["rotatecount"] = rotatecount
        if logcompressiontype is not UNSET:
            field_dict["logcompressiontype"] = logcompressiontype
        if enableremotelogging is not UNSET:
            field_dict["enableremotelogging"] = enableremotelogging
        if ipprotocol is not UNSET:
            field_dict["ipprotocol"] = ipprotocol
        if sourceip is not UNSET:
            field_dict["sourceip"] = sourceip
        if remoteserver is not UNSET:
            field_dict["remoteserver"] = remoteserver
        if remoteserver2 is not UNSET:
            field_dict["remoteserver2"] = remoteserver2
        if remoteserver3 is not UNSET:
            field_dict["remoteserver3"] = remoteserver3
        if logall is not UNSET:
            field_dict["logall"] = logall
        if filter_ is not UNSET:
            field_dict["filter"] = filter_
        if dhcp is not UNSET:
            field_dict["dhcp"] = dhcp
        if auth is not UNSET:
            field_dict["auth"] = auth
        if portalauth is not UNSET:
            field_dict["portalauth"] = portalauth
        if vpn is not UNSET:
            field_dict["vpn"] = vpn
        if dpinger is not UNSET:
            field_dict["dpinger"] = dpinger
        if hostapd is not UNSET:
            field_dict["hostapd"] = hostapd
        if system is not UNSET:
            field_dict["system"] = system
        if resolver is not UNSET:
            field_dict["resolver"] = resolver
        if ppp is not UNSET:
            field_dict["ppp"] = ppp
        if routing is not UNSET:
            field_dict["routing"] = routing
        if ntpd is not UNSET:
            field_dict["ntpd"] = ntpd

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        _format_ = d.pop("format", UNSET)
        format_: LogSettingsFormat | Unset
        if isinstance(_format_, Unset):
            format_ = UNSET
        else:
            format_ = LogSettingsFormat(_format_)

        reverseorder = d.pop("reverseorder", UNSET)

        nentries = d.pop("nentries", UNSET)

        nologdefaultblock = d.pop("nologdefaultblock", UNSET)

        nologdefaultpass = d.pop("nologdefaultpass", UNSET)

        nologbogons = d.pop("nologbogons", UNSET)

        nologprivatenets = d.pop("nologprivatenets", UNSET)

        nolognginx = d.pop("nolognginx", UNSET)

        rawfilter = d.pop("rawfilter", UNSET)

        disablelocallogging = d.pop("disablelocallogging", UNSET)

        logconfigchanges = d.pop("logconfigchanges", UNSET)

        _filterdescriptions = d.pop("filterdescriptions", UNSET)
        filterdescriptions: LogSettingsFilterdescriptions | Unset
        if isinstance(_filterdescriptions, Unset):
            filterdescriptions = UNSET
        else:
            filterdescriptions = LogSettingsFilterdescriptions(_filterdescriptions)

        logfilesize = d.pop("logfilesize", UNSET)

        rotatecount = d.pop("rotatecount", UNSET)

        _logcompressiontype = d.pop("logcompressiontype", UNSET)
        logcompressiontype: LogSettingsLogcompressiontype | Unset
        if isinstance(_logcompressiontype, Unset):
            logcompressiontype = UNSET
        else:
            logcompressiontype = LogSettingsLogcompressiontype(_logcompressiontype)

        enableremotelogging = d.pop("enableremotelogging", UNSET)

        _ipprotocol = d.pop("ipprotocol", UNSET)
        ipprotocol: LogSettingsIpprotocol | Unset
        if isinstance(_ipprotocol, Unset):
            ipprotocol = UNSET
        else:
            ipprotocol = LogSettingsIpprotocol(_ipprotocol)

        sourceip = d.pop("sourceip", UNSET)

        def _parse_remoteserver(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        remoteserver = _parse_remoteserver(d.pop("remoteserver", UNSET))

        def _parse_remoteserver2(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        remoteserver2 = _parse_remoteserver2(d.pop("remoteserver2", UNSET))

        def _parse_remoteserver3(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        remoteserver3 = _parse_remoteserver3(d.pop("remoteserver3", UNSET))

        logall = d.pop("logall", UNSET)

        filter_ = d.pop("filter", UNSET)

        dhcp = d.pop("dhcp", UNSET)

        auth = d.pop("auth", UNSET)

        portalauth = d.pop("portalauth", UNSET)

        vpn = d.pop("vpn", UNSET)

        dpinger = d.pop("dpinger", UNSET)

        hostapd = d.pop("hostapd", UNSET)

        system = d.pop("system", UNSET)

        resolver = d.pop("resolver", UNSET)

        ppp = d.pop("ppp", UNSET)

        routing = d.pop("routing", UNSET)

        ntpd = d.pop("ntpd", UNSET)

        patch_status_logs_settings_endpoint_data_body = cls(
            format_=format_,
            reverseorder=reverseorder,
            nentries=nentries,
            nologdefaultblock=nologdefaultblock,
            nologdefaultpass=nologdefaultpass,
            nologbogons=nologbogons,
            nologprivatenets=nologprivatenets,
            nolognginx=nolognginx,
            rawfilter=rawfilter,
            disablelocallogging=disablelocallogging,
            logconfigchanges=logconfigchanges,
            filterdescriptions=filterdescriptions,
            logfilesize=logfilesize,
            rotatecount=rotatecount,
            logcompressiontype=logcompressiontype,
            enableremotelogging=enableremotelogging,
            ipprotocol=ipprotocol,
            sourceip=sourceip,
            remoteserver=remoteserver,
            remoteserver2=remoteserver2,
            remoteserver3=remoteserver3,
            logall=logall,
            filter_=filter_,
            dhcp=dhcp,
            auth=auth,
            portalauth=portalauth,
            vpn=vpn,
            dpinger=dpinger,
            hostapd=hostapd,
            system=system,
            resolver=resolver,
            ppp=ppp,
            routing=routing,
            ntpd=ntpd,
        )

        patch_status_logs_settings_endpoint_data_body.additional_properties = d
        return patch_status_logs_settings_endpoint_data_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
