from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.certificate_authority_generate_keylen import CertificateAuthorityGenerateKeylen
from ..models.certificate_authority_generate_keytype import CertificateAuthorityGenerateKeytype
from ..types import UNSET, Unset

T = TypeVar("T", bound="PostSystemCertificateAuthorityGenerateEndpointDataBody")


@_attrs_define
class PostSystemCertificateAuthorityGenerateEndpointDataBody:
    """
    Attributes:
        descr (str): The descriptive name for this certificate authority.<br>
        caref (str): The certificate authority to use as the parent for this intermediate certificate
            authority.<br><br>This field is only available when the following conditions are met:<br>- `is_intermediate`
            must be equal to `true`<br>
        keytype (CertificateAuthorityGenerateKeytype): The type of key pair to generate.<br>
        keylen (CertificateAuthorityGenerateKeylen): The length of the RSA key pair to generate.<br><br>This field is
            only available when the following conditions are met:<br>- `keytype` must be equal to `'RSA'`<br>
        ecname (str): The name of the elliptic curve to use for the ECDSA key pair.<br><br>This field is only available
            when the following conditions are met:<br>- `keytype` must be equal to `'ECDSA'`<br>
        digest_alg (str): The digest algorithm to use when signing certificates.<br>
        refid (None | str | Unset): The unique ID assigned to this certificate authority for internal system use. This
            value is generated by this system and cannot be changed.<br>
        trust (bool | Unset): Adds or removes this certificate authority from the operating system's trust stored.<br>
        randomserial (bool | Unset): Enables or disables the randomization of serial numbers for certificates signed by
            this CA.<br>
        serial (int | None | Unset): The decimal number to be used as a sequential serial number for the next
            certificate to be signed by this CA. This value is ignored when Randomize Serial is checked.<br> Default: 1.
        is_intermediate (bool | Unset): Indicates if this certificate authority is an intermediate certificate
            authority.<br>
        lifetime (int | Unset): The number of days the certificate authority is valid for.<br> Default: 3650.
        dn_commonname (str | Unset): The common name for the certificate authority.<br> Default: 'internal-ca'.
        dn_country (str | Unset): The country for the certificate authority.<br>
        dn_state (str | Unset): The state for the certificate authority.<br>
        dn_city (str | Unset): The city for the certificate authority.<br>
        dn_organization (str | Unset): The organization for the certificate authority.<br>
        dn_organizationalunit (str | Unset): The organizational unit for the certificate authority.<br>
        crt (None | str | Unset): The X509 certificate string.<br>
        prv (None | str | Unset): The X509 private key string.<br>
    """

    descr: str
    caref: str
    keytype: CertificateAuthorityGenerateKeytype
    keylen: CertificateAuthorityGenerateKeylen
    ecname: str
    digest_alg: str
    refid: None | str | Unset = UNSET
    trust: bool | Unset = UNSET
    randomserial: bool | Unset = UNSET
    serial: int | None | Unset = 1
    is_intermediate: bool | Unset = UNSET
    lifetime: int | Unset = 3650
    dn_commonname: str | Unset = "internal-ca"
    dn_country: str | Unset = UNSET
    dn_state: str | Unset = UNSET
    dn_city: str | Unset = UNSET
    dn_organization: str | Unset = UNSET
    dn_organizationalunit: str | Unset = UNSET
    crt: None | str | Unset = UNSET
    prv: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        descr = self.descr

        caref = self.caref

        keytype = self.keytype.value

        keylen = self.keylen.value

        ecname = self.ecname

        digest_alg = self.digest_alg

        refid: None | str | Unset
        if isinstance(self.refid, Unset):
            refid = UNSET
        else:
            refid = self.refid

        trust = self.trust

        randomserial = self.randomserial

        serial: int | None | Unset
        if isinstance(self.serial, Unset):
            serial = UNSET
        else:
            serial = self.serial

        is_intermediate = self.is_intermediate

        lifetime = self.lifetime

        dn_commonname = self.dn_commonname

        dn_country = self.dn_country

        dn_state = self.dn_state

        dn_city = self.dn_city

        dn_organization = self.dn_organization

        dn_organizationalunit = self.dn_organizationalunit

        crt: None | str | Unset
        if isinstance(self.crt, Unset):
            crt = UNSET
        else:
            crt = self.crt

        prv: None | str | Unset
        if isinstance(self.prv, Unset):
            prv = UNSET
        else:
            prv = self.prv

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "descr": descr,
                "caref": caref,
                "keytype": keytype,
                "keylen": keylen,
                "ecname": ecname,
                "digest_alg": digest_alg,
            }
        )
        if refid is not UNSET:
            field_dict["refid"] = refid
        if trust is not UNSET:
            field_dict["trust"] = trust
        if randomserial is not UNSET:
            field_dict["randomserial"] = randomserial
        if serial is not UNSET:
            field_dict["serial"] = serial
        if is_intermediate is not UNSET:
            field_dict["is_intermediate"] = is_intermediate
        if lifetime is not UNSET:
            field_dict["lifetime"] = lifetime
        if dn_commonname is not UNSET:
            field_dict["dn_commonname"] = dn_commonname
        if dn_country is not UNSET:
            field_dict["dn_country"] = dn_country
        if dn_state is not UNSET:
            field_dict["dn_state"] = dn_state
        if dn_city is not UNSET:
            field_dict["dn_city"] = dn_city
        if dn_organization is not UNSET:
            field_dict["dn_organization"] = dn_organization
        if dn_organizationalunit is not UNSET:
            field_dict["dn_organizationalunit"] = dn_organizationalunit
        if crt is not UNSET:
            field_dict["crt"] = crt
        if prv is not UNSET:
            field_dict["prv"] = prv

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        descr = d.pop("descr")

        caref = d.pop("caref")

        keytype = CertificateAuthorityGenerateKeytype(d.pop("keytype"))

        keylen = CertificateAuthorityGenerateKeylen(d.pop("keylen"))

        ecname = d.pop("ecname")

        digest_alg = d.pop("digest_alg")

        def _parse_refid(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        refid = _parse_refid(d.pop("refid", UNSET))

        trust = d.pop("trust", UNSET)

        randomserial = d.pop("randomserial", UNSET)

        def _parse_serial(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        serial = _parse_serial(d.pop("serial", UNSET))

        is_intermediate = d.pop("is_intermediate", UNSET)

        lifetime = d.pop("lifetime", UNSET)

        dn_commonname = d.pop("dn_commonname", UNSET)

        dn_country = d.pop("dn_country", UNSET)

        dn_state = d.pop("dn_state", UNSET)

        dn_city = d.pop("dn_city", UNSET)

        dn_organization = d.pop("dn_organization", UNSET)

        dn_organizationalunit = d.pop("dn_organizationalunit", UNSET)

        def _parse_crt(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        crt = _parse_crt(d.pop("crt", UNSET))

        def _parse_prv(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        prv = _parse_prv(d.pop("prv", UNSET))

        post_system_certificate_authority_generate_endpoint_data_body = cls(
            descr=descr,
            caref=caref,
            keytype=keytype,
            keylen=keylen,
            ecname=ecname,
            digest_alg=digest_alg,
            refid=refid,
            trust=trust,
            randomserial=randomserial,
            serial=serial,
            is_intermediate=is_intermediate,
            lifetime=lifetime,
            dn_commonname=dn_commonname,
            dn_country=dn_country,
            dn_state=dn_state,
            dn_city=dn_city,
            dn_organization=dn_organization,
            dn_organizationalunit=dn_organizationalunit,
            crt=crt,
            prv=prv,
        )

        post_system_certificate_authority_generate_endpoint_data_body.additional_properties = d
        return post_system_certificate_authority_generate_endpoint_data_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
