from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.certificate_revocation_list_method import CertificateRevocationListMethod
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.certificate_revocation_list_cert_item import CertificateRevocationListCertItem


T = TypeVar("T", bound="PostSystemCRLEndpointJsonBody")


@_attrs_define
class PostSystemCRLEndpointJsonBody:
    """
    Attributes:
        caref (str): The unique ID of the CA that this CRL is associated with.<br>
        descr (str): The unique name/description for this CRL.<br>
        method (CertificateRevocationListMethod): The method used to generate this CRL.<br>
        text (str): The raw x509 CRL data.<br><br>This field is only available when the following conditions are
            met:<br>- `method` must be equal to `'existing'`<br>
        refid (None | str | Unset): The unique ID for this CRL. This is automatically generated by the system and cannot
            be changed.<br>
        lifetime (int | Unset): The lifetime of this CRL in days.<br><br>This field is only available when the following
            conditions are met:<br>- `method` must be equal to `'internal'`<br> Default: 730.
        serial (int | Unset): The serial number of the CRL.<br><br>This field is only available when the following
            conditions are met:<br>- `method` must be equal to `'internal'`<br>
        cert (list[CertificateRevocationListCertItem] | Unset): The list of revoked certificates in this
            CRL.<br><br>This field is only available when the following conditions are met:<br>- `method` must be equal to
            `'internal'`<br>
    """

    caref: str
    descr: str
    method: CertificateRevocationListMethod
    text: str
    refid: None | str | Unset = UNSET
    lifetime: int | Unset = 730
    serial: int | Unset = UNSET
    cert: list[CertificateRevocationListCertItem] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        caref = self.caref

        descr = self.descr

        method = self.method.value

        text = self.text

        refid: None | str | Unset
        if isinstance(self.refid, Unset):
            refid = UNSET
        else:
            refid = self.refid

        lifetime = self.lifetime

        serial = self.serial

        cert: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.cert, Unset):
            cert = []
            for cert_item_data in self.cert:
                cert_item = cert_item_data.to_dict()
                cert.append(cert_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "caref": caref,
                "descr": descr,
                "method": method,
                "text": text,
            }
        )
        if refid is not UNSET:
            field_dict["refid"] = refid
        if lifetime is not UNSET:
            field_dict["lifetime"] = lifetime
        if serial is not UNSET:
            field_dict["serial"] = serial
        if cert is not UNSET:
            field_dict["cert"] = cert

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.certificate_revocation_list_cert_item import CertificateRevocationListCertItem

        d = dict(src_dict)
        caref = d.pop("caref")

        descr = d.pop("descr")

        method = CertificateRevocationListMethod(d.pop("method"))

        text = d.pop("text")

        def _parse_refid(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        refid = _parse_refid(d.pop("refid", UNSET))

        lifetime = d.pop("lifetime", UNSET)

        serial = d.pop("serial", UNSET)

        _cert = d.pop("cert", UNSET)
        cert: list[CertificateRevocationListCertItem] | Unset = UNSET
        if _cert is not UNSET:
            cert = []
            for cert_item_data in _cert:
                cert_item = CertificateRevocationListCertItem.from_dict(cert_item_data)

                cert.append(cert_item)

        post_system_crl_endpoint_json_body = cls(
            caref=caref,
            descr=descr,
            method=method,
            text=text,
            refid=refid,
            lifetime=lifetime,
            serial=serial,
            cert=cert,
        )

        post_system_crl_endpoint_json_body.additional_properties = d
        return post_system_crl_endpoint_json_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
